---
title: "DPE_RTest"
author: "Reinp"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: 
    keep_md: yes
  word_document: default
---

# R Programming

## Set Chunk requirements

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
#echo=FALSE indicates that the code will not be shown in the final document 
#(though any results/output would still be displayed).
#include=FALSE to have the chunk evaluated, but neither the code nor its output displayed
# warning=FALSE and message=FALSE suppress any R warnings or messages from being included 
#in the final document
```

## loading Relevant packages and Data Set
```{r}
library(plyr)
library(tidyverse)
## tidyverse includes readr, ggplot2, dplyr, forcats, tibble, tidyr, purrr, stringr
library(stats)
library(psych)


## Reading our dataset
setwd('E:/Documents/Reinp/GitHub Respositories/DPE_RTest')

R_test <- read_csv("R_test_dataset.csv")
View(R_test)
attach(R_test)

```

## Structure of the data
```{r}

head(R_test)

tail(R_test)

## How many variables and observations are there?
ncol(R_test)

nrow(R_test)

##learn more about the dataset
help(R_test)
??R_test


str(R_test)
class(R_test)
typeof(R_test) 
length(R_test) #number of variables
names(R_test) #display variable names

#attributes(R_test) names(R_test), class(R_test), row.names(R_test)

```


## Missing data
```{r}
complete.cases(R_test) ##print logical vector indicating complete rows
                       ##(i.e. rows without NA)

which(!complete.cases(R_test)) #print incomplete cases (rows with NA)

#R_test[complete.cases(R_test), ] ## Keep only the complete rows

#data_complete <- R_test[complete.cases(R_test), ] ## Store the complete cases subset in a new
                                                   ##data frame

which(is.na(R_test)) #check for missing values
sum(is.na(R_test))

```

## Duplicated Cases
```{r}
duplicated(R_test$SbjNum)
sum(duplicated(R_test$SbjNum))
table(duplicated(R_test$SbjNum))

mean(duplicated(R_test$SbjNum)) #proportion of repeat cases

sum(duplicated(R_test$SbjNum))/nrow(R_test)
```

## unique cases
```{r}

#unique(R_test$SbjNum)
#count(unique(R_test$SbjNum))
#table(unique(R_test$SbjNum))

## data with unique SbjNum

R_testu <- R_test[!duplicated(R_test$SbjNum),]
View(R_testu)
attach(R_testu)

nrow(R_testu)
```

## Assigning value labels to variables
```{r}
R_testu$Interviewer <- factor(R_testu$Interviewer,
levels = c(1,2,3,4,5,6,7,8,9,10,11,12,13),
labels = c("Menya Abdmajid", "Bbale Denis", "Muwonge Allan Joshua", "Wambi Ken Paul", 
           "Wabwire Thomas", "Muhindo Wilfred", "Ahumuza Owen", "Mirembe Mary",
           "Arinitwe Mackline", "Alum Maria", "Kasule violet", "Aweko Monica", 
           "Nabbumba Pennina"))

R_testu$S2 <- factor(R_testu$S2,
levels = c(1,2,3,4),
labels = c("17 and below", "18-25", "25-30", "31 and above"))

R_testu$Social_Class <- factor(R_testu$Social_Class,
levels = c(1,2,3,4,5),
labels = c("Social Class D", "Social Class C2", "Social Class C1", "Social Class B", 
           "Social Class A"))

R_testu$B4 <- factor(R_testu$B4,
levels = c(1,2),
labels = c("Yes", "No"))

R_testu$B17 <- factor(R_testu$B17,
levels = c(1,2,3,4,5),
labels = c("Extremely ready", "Somewhat ready", "Neutral", "Not ready", "Definitely not ready"))

R_testu$C1 <- factor(R_testu$C1,
levels = c(1,2,3,4,5),
labels = c("I have been employed (for example in an office, restaurant,", 
           "I am self-employed (for example, on my own farm or family's", 
           "I have been employed as an unpaid intern", 
           "I have been engaged in household activities including agricu", 
           "I have not been employed"))

```


## Distribution of variables
```{r}

#DollarSign Syntax
table(R_testu$Interviewer)

which(is.na(R_testu$Ward)) #check for missing values in ward

R_testu$Ward <- gsub("Bukoto Nsimbi ziwome", "Bukoto", R_testu$Ward)
R_testu$Ward <- gsub("Bukoto Nsimbi Ziwome", "Bukoto", R_testu$Ward)
R_testu$Ward <- gsub("Bukoto church", "Bukoto", R_testu$Ward)

R_testu$Ward <- gsub("KABOWA", "Kabowa", R_testu$Ward)
R_testu$Ward <- gsub("kabowa", "Kabowa", R_testu$Ward)
R_testu$Ward <- gsub("Kafumbe mukasa", "Kafumbe Mukasa", R_testu$Ward)
R_testu$Ward <- gsub("kagugube", "Kagugube", R_testu$Ward)
R_testu$Ward <- gsub("kamokya", "Kamwokya", R_testu$Ward)
R_testu$Ward <- gsub("KAMWOKYA", "Kamwokya", R_testu$Ward)
R_testu$Ward <- gsub("kansanga", "Kansanga", R_testu$Ward)
R_testu$Ward <- gsub("kasanga", "Kansanga", R_testu$Ward)
R_testu$Ward <- gsub("Kansanga kiwafu Estates", "Kansanga", R_testu$Ward)
R_testu$Ward <- gsub("kanyanya - komamboga zone A", "Kanyanya zone", R_testu$Ward)
R_testu$Ward <- gsub("kanyanya central zone 1", "Kanyanya zone", R_testu$Ward)
R_testu$Ward <- gsub("Kanyanya central zone B", "Kanyanya zone", R_testu$Ward)
R_testu$Ward <- gsub("kasubi", "Kasubi", R_testu$Ward)
R_testu$Ward <- gsub("KASUBI", "Kasubi", R_testu$Ward)
R_testu$Ward <- gsub("kawaala", "Kawaala", R_testu$Ward)
R_testu$Ward <- gsub("Kinawataka zone 1", "Kinawataka", R_testu$Ward)
R_testu$Ward <- gsub("KISASI DUNGU ZONE", "Dungu Zone", R_testu$Ward)
R_testu$Ward <- gsub("kisenyi", "Kisenyi", R_testu$Ward)
R_testu$Ward <- gsub("KISENYI", "Kisenyi", R_testu$Ward)
R_testu$Ward <- gsub("Kisenyi zone 3", "Kisenyi", R_testu$Ward)
R_testu$Ward <- gsub("kisira zone", "Kisira zone", R_testu$Ward)
R_testu$Ward <- gsub("kisugu", "Kisugu", R_testu$Ward)
R_testu$Ward <- gsub("Kisugu Upper Zone", "Kisugu", R_testu$Ward)
R_testu$Ward <- gsub("kiwatule", "Kiwatule", R_testu$Ward)
R_testu$Ward <- gsub("Kiwatule  kinyarwanda", "Kinyarwanda zone", R_testu$Ward)
R_testu$Ward <- gsub("Kiwatule kinyarwanda", "Kinyarwanda zone", R_testu$Ward)

R_testu$Ward <- gsub("lugala", "Lugala", R_testu$Ward)
R_testu$Ward <- gsub("Luwafu kirundu zone", "kiruddu", R_testu$Ward)

R_testu$Ward <- gsub("Makerere  University", "MAKERERE", R_testu$Ward)
R_testu$Ward <- gsub("Makerere Kagugube", "Kagugube", R_testu$Ward)
R_testu$Ward <- gsub("Makerere Kakugube", "Kagugube", R_testu$Ward)
R_testu$Ward <- gsub("makerere kakugube zone", "Kagugube", R_testu$Ward)
R_testu$Ward <- gsub("MAKERERE KAVULE", "Makerere kavule", R_testu$Ward)
R_testu$Ward <- gsub("Makerere kivulu", "Kivulu", R_testu$Ward)
R_testu$Ward <- gsub("Makerere Kivulu", "Kivulu", R_testu$Ward)
R_testu$Ward <- gsub("Mamerere Kagugube", "Kagugube", R_testu$Ward)
R_testu$Ward <- gsub("Makindyd Luwafu", "Makindye", R_testu$Ward)
R_testu$Ward <- gsub("makindye luwafu", "Makindye", R_testu$Ward)
R_testu$Ward <- gsub("Makindye luwafu", "Makindye", R_testu$Ward)
R_testu$Ward <- gsub("Makindye Luwafu", "Makindye", R_testu$Ward)
R_testu$Ward <- gsub("Makindye luwafu kirundu", "kiruddu", R_testu$Ward)
R_testu$Ward <- gsub("Makindye kirundu", "kiruddu", R_testu$Ward)
R_testu$Ward <- gsub("masanafu", "Masanafu", R_testu$Ward)
R_testu$Ward <- gsub("MASANAFU", "Masanafu", R_testu$Ward)
R_testu$Ward <- gsub("MBUYA", "Mbuya", R_testu$Ward)
R_testu$Ward <- gsub("Mbuya 1", "Mbuya", R_testu$Ward)
R_testu$Ward <- gsub("Mbuya kaggo", "Mbuya", R_testu$Ward)
R_testu$Ward <- gsub("Mbuya Kaggo", "Mbuya", R_testu$Ward)
R_testu$Ward <- gsub("Mbuya zone 1", "Mbuya", R_testu$Ward)
R_testu$Ward <- gsub("Mbuya kinawataka", "Kinawataka", R_testu$Ward)
R_testu$Ward <- gsub("Mulago ward C", "Mulago", R_testu$Ward)
R_testu$Ward <- gsub("Mutungo  Some 4", "Mutungo", R_testu$Ward)
R_testu$Ward <- gsub("Mutungo Biina", "Mutungo", R_testu$Ward)
R_testu$Ward <- gsub("Mutungo zone 4", "Mutungo", R_testu$Ward)
R_testu$Ward <- gsub("Mutungo Zone 4", "Mutungo", R_testu$Ward)
R_testu$Ward <- gsub("Mutungu", "Mutungo", R_testu$Ward)
R_testu$Ward <- gsub("Mutungo  Kampala road", "KAMPALA ROAD", R_testu$Ward)
R_testu$Ward <- gsub("Mutungo Kampala road", "KAMPALA ROAD", R_testu$Ward)

R_testu$Ward <- gsub("NABWERU ZONE 1", "Nabweru", R_testu$Ward)
R_testu$Ward <- gsub("nabweru zone1", "Nabweru", R_testu$Ward)
R_testu$Ward <- gsub("NAGURU BARRACKS", "NAGURU", R_testu$Ward)
R_testu$Ward <- gsub("NAKULABYE", "Nakulabye", R_testu$Ward)
R_testu$Ward <- gsub("NALUKABYE", "Nakulabye", R_testu$Ward)
R_testu$Ward <- gsub("NANKULABYE", "Nakulabye", R_testu$Ward)

R_testu$Ward <- gsub("NAMUNGONA", "Namungoona", R_testu$Ward)
R_testu$Ward <- gsub("Namungona Kisugu", "Namungoona", R_testu$Ward)
R_testu$Ward <- gsub("nsambya", "Nsambya", R_testu$Ward)
R_testu$Ward <- gsub("Nsambya  Barracks.", "Nsambya", R_testu$Ward)
R_testu$Ward <- gsub("Nsambya barracks", "Nsambya", R_testu$Ward)
R_testu$Ward <- gsub("Nsambya Barracks", "Nsambya", R_testu$Ward)
R_testu$Ward <- gsub("Nsambya kevina", "Nsambya", R_testu$Ward)
R_testu$Ward <- gsub("Nsambya Kevina", "Nsambya", R_testu$Ward)

R_testu$Ward <- gsub("Sebagala Zone", "Sebaggala zone", R_testu$Ward)
R_testu$Ward <- gsub("wandegeya.junju road", "Wandegeya", R_testu$Ward)
R_testu$Ward <- gsub("WANDEGEYA", "Wandegeya", R_testu$Ward)
R_testu$Ward <- gsub("wankulukuku", "Wankulukuku", R_testu$Ward)
R_testu$Ward <- gsub("WANKULUKUKU", "Wankulukuku", R_testu$Ward)
R_testu$Ward <- gsub("WUNKULUKUKU", "Wankulukuku", R_testu$Ward)

table(R_testu$Ward)

table(R_testu$Ward, R_testu$Interviewer)

table(R_testu$Interviewer, R_testu$Ward)

table(R_testu$Social_Class, R_testu$A2)

table(R_testu$A2, R_testu$Social_Class)
```


## Descriptive Statistics

```{r}
library(mosaic)
#favstats(~A2, data=R_testu)
favstats(~A2, data=R_testu)[c("min", "max", "mean","median")]

#favstats(~B16, data=R_testu)
favstats(~B16, data=R_testu)[c("min", "max", "mean","median")]

```

## ggplot- lineplot

```{r}

R_testuplot <- R_testu%>%
group_by(A2) %>%
summarise(B16 = mean(B16))


ggplot(R_testuplot, aes(A2, B16))+
  labs(title="Avearage amount willing to be paid for next degree/diploma", 
       x="Age of Respondents", y="Amount per Semester") +
  theme(axis.title=element_text(face="bold.italic", size="12", color="brown"), 
        axis.text = element_text(size = 8, face="bold"), 
        plot.title=element_text(size=12, face="bold", color="red", hjust = 0.5))+
  geom_point(size=2)+
  geom_line(colour="blue", size=1)+
  geom_text(aes(label=R_testuplot$A2), nudge_x = 0.2, size=3)+
  scale_x_continuous(breaks = c(16, 18, 20, 22, 24, 26, 28, 30, 32), limits=c(17,31))+
  scale_y_continuous(breaks = c(0, 200000, 400000, 600000, 800000, 1000000, 1200000), 
                     limits=c(0,1200000))
  
#If the plot is on the screen ggsave(“path/filename.png”)

#If you have a plot object ggsave(myplot, file=“path/filename.png”)

#Specify size ggsave(myplot, “path/filename.png”, width=6, height=4)

# any plot format (pdf, png, eps, svg, jpg)


```

## ggplot Scatterplot
```{r}

ggplot(R_testu, aes(A2, B16))+
  labs(title="Amount willing to be paid for next degree/diploma", 
       x="Age of Respondents", y="Amount per Semester") +
  theme(axis.title=element_text(face="bold.italic", size="12", color="brown"), 
        axis.text = element_text(size = 8, face="bold"), 
        plot.title=element_text(size=12, face="bold", color="red", hjust = 0.5))+
  geom_point(size=2)+
  scale_x_continuous(breaks = c(16, 18, 20, 22, 24, 26, 28, 30, 32), limits=c(17,31))+
  scale_y_continuous(breaks = c(0, 250000, 500000, 750000, 1000000, 1250000, 1500000, 
                  1750000, 2000000, 2250000, 2500000, 2750000, 3000000, 3250000),
                  limits=c(0,3250000))

```

## Proportion
```{r}
#Your school an all secondary girls school?
table(R_testu$B4)

prop.table(table(R_testu$B4))

```

## Filter data
```{r}



```


## Additional Analysis
```{r}

nrow(R_test)
nrow(R_testu)

R_testu1 = subset(R_testu, select = -c(Q_25_S,Q_32_S) ) #Delete column by name

R_testu1 <- na.omit(R_testu1) # Getting rid of missing data
View(R_testu1)
attach(R_testu1)
nrow(R_testu1)

which(is.na(R_testu1)) #check for missing values
sum(is.na(R_testu1))

library(car)
library(MASS) #So that distributions that must be non-zero can make sense of my data


qqp(R_testu1$B16+1, "norm", main="Q-Q Plot ~ Normal model")

qqp(R_testu1$B16+1, "lnorm", main="Q-Q Plot ~ LogNormal model") #lnorm is lognormal

qqp(R_testu1$B16+1, "exp", main="Q-Q Plot ~ Exponential model")

#qqp requires estimates of the parameters of the negative binomial, Poisson
# and gamma distributions. You can generate estimates using the fitdistr function.
#negative binomial and gamma distributions can only handle positive numbers.
#Poisson distribution can only handle positive whole numbers.
#Binomial and Poisson distributions are different from the others because they are
#discrete rather than continuous, which means they quantify distinct,
#countable events or the probability of these events

nbinom <- fitdistr(R_testu$B16+1, "Negative Binomial")
qqp(R_testu$B16+1, "nbinom", size = nbinom$estimate[[1]], mu =
nbinom$estimate[[2]], main="Q-Q Plot ~ Negative Binomial model")

pois <- fitdistr(R_testu1$B16+1, "Poisson")
qqp(R_testu1$B16+1, "pois", lambda=pois$estimate, main="Q-Q Plot ~ Poisson model")

gamma <- fitdistr(R_testu1$B16+1, "gamma",
list(shape = 1, rate = 0.1), lower = 0.4)
qqp(R_testu1$B16+1, "gamma", shape = gamma$estimate[[1]], rate =
gamma$estimate[[2]], main="Q-Q Plot ~ Gamma model")

weibull <- fitdistr(R_testu1$B16+1, "weibull")
qqp(R_testu1$B16+1, "weibull", shape = weibull$estimate[[1]],
scale=weibull$estimate[[2]], main="Q-Q Plot ~ Weibull model")



```





















